### ISSUE TITLE
Critical Error: Call to undefined method Unirest\Request::enableRetries()

### ISSUE THREAD

**Issue by thisissandip** [woocommerce/woocommerce-square#15]
### Describe the bug

A user completed the Square setup and got a critical error:
<img width="1055" alt="212613919-8d6fc14c-f80d-4763-b2b1-f10f3600d199-2" src="https://github.com/woocommerce/woocommerce-square-private/assets/407542/292cc58f-9375-4bfe-beb3-4214f9b798f8">

Fatal error logs:

```
2023-01-16T00:03:34+00:00 CRITICAL Uncaught Error: Call to undefined method Unirest\Request::enableRetries() in {redacted}/wp-content/plugins/woocommerce-square/vendor/square/square/src/Apis/BaseApi.php:64
Stack trace:
#0 {redacted}/wp-content/plugins/woocommerce-square/vendor/square/square/src/Apis/InventoryApi.php(23): Square\Apis\BaseApi->__construct(Object(Square\SquareClient), Array, NULL)
woocommerce/woocommerce-square-private#1 {redacted}/wp-content/plugins/woocommerce-square/vendor/square/square/src/SquareClient.php(537): Square\Apis\InventoryApi->__construct(Object(Square\SquareClient), Array, NULL)
woocommerce/woocommerce-square-private#2 {redacted}/wp-content/plugins/woocommerce-square/includes/API/Requests/Inventory.php(46): Square\SquareClient->getInventoryApi()
woocommerce/woocommerce-square-private#3 {redacted}/wp-content/plugins/woocommerce-square/includes/API.php(693): WooCommerce\Square\API\Requests\Inventory->__construct(Object(Square\SquareClient))
woocommerce/woocommerce-square-private#4 {redacted}/wp-content/plugins/woocommerce-square/includes/API.php(670): WooCommerce\Square\API->get_new_reque in {redacted}/wp-content/plugins/woocommerce-square/vendor/square/square/src/Apis/BaseApi.php on line 64
```

### To reproduce

I haven't been able to reproduce it. The user ran into this error after they set up Square.

### Expected behavior

No errors should be there while setting up the plugin.

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - WooCommerce Square Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

### Additional details

5862268-zen

**Comment by jeffpaul** [comment]
Closing as not currently a priority, but if this becomes a particularly high impact and priority with merchants then please re-open for us to re-triage... thanks!
