### ISSUE TITLE
Fatal error while Changing subscription Payment Method 

### ISSUE THREAD

**Issue by qasumitbagthariya** [woocommerce/woocommerce-square#150]
### Describe the bug
Unable to change payment method on the Subscription page. When attempting to update the payment method

### To reproduce

1. Goto may account > Subscription
2. Select any subscription and change payment method
3.  Make sure to check mark "Use this payment method for all of my current subscriptions"

**Screenshots**
![image](https://github.com/woocommerce/woocommerce-square/assets/67687255/9e732d54-4c67-4858-a611-6df78d3f5545)

```
[09-Jun-2024 18:49:41 UTC] PHP Fatal error:  Uncaught Error: Call to a member function payment_method_supports() on false in /Users/sumitbagthariya/Local Sites/square/app/public/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-change-payment-gateway.php:423
Stack trace:
#0 /Users/sumitbagthariya/Local Sites/square/app/public/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-change-payment-gateway.php(373): WC_Subscriptions_Change_Payment_Gateway::update_all_payment_methods_from_subscription(Object(WC_Subscription), 'square_credit_c...')
#1 /Users/sumitbagthariya/Local Sites/square/app/public/wp-includes/class-wp-hook.php(324): WC_Subscriptions_Change_Payment_Gateway::change_payment_method_via_pay_shortcode('')
#2 /Users/sumitbagthariya/Local Sites/square/app/public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /Users/sumitbagthariya/Local Sites/square/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /Users/sumitbagthariya/Local Sites/square/app/public/wp-settings.php(717): do_action('wp_loaded')
#5 /Users/sumitbagthariya/Local Sites/square/app/public/wp-config.php(114): require_once('/Users/sumitbag...')
#6 /Users/sumitbagthariya/Local Sites/square/app/public/wp-load.php(50): require_once('/Users/sumitbag...')
#7 /Users/sumitbagthariya/Local Sites/square/app/public/wp-blog-header.php(13): require_once('/Users/sumitbag...')
#8 /Users/sumitbagthariya/Local Sites/square/app/public/index.php(17): require('/Users/sumitbag...')
#9 {main}
  thrown in /Users/sumitbagthariya/Local Sites/square/app/public/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-change-payment-gateway.php on line 423

```
### Expected behavior
Allow users to seamlessly update their payment method without encountering any errors.

**Environment (please complete the following information):**
 - WordPress Version - 6.5.4
 - WooCommerce Version  - 8.9.2
 - WooCommerce Square Plugin Version. - 4.6.2
 - Browser [e.g. chrome, safari] and Version - chrome
 - Any other plugins installed-  WooCommerce Subscriptions 6.3.2

### Additional details

<details><summary>System status</summary>
  
  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
</details>

**Comment by qasumitbagthariya** [comment]
I've tried reproducing the issue with a fresh setup (instawp) but couldn't encounter it. Based on our internal discussions with @Sidsector9 @iamdharmesh, it seems the problem occurred due to local setup issues. Therefore, we need to close this issue. Additionally, share a video as proof. 


https://github.com/woocommerce/woocommerce-square/assets/67687255/700717ba-8630-40c3-8459-69613686be09



**Testing Environment** 

<Details>

- WordPress: 6.5.4
- WooCommerce Subscription - 6.4.0
- Theme: Twenty Twenty-Four 1.1
- WooCommerce - 9.0.0
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: trunk

</Details>

cc @jeffpaul @dkotter
