### ISSUE TITLE
Fatal error/warning Unsupported operand types: int * string in Digital_Wallet.php:462

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-square#187]
### Describe the bug

```
2024-07-25T01:04:53+00:00 Critical Uncaught TypeError: Unsupported operand types: int * string in /public_html/wp-content/plugins/woocommerce-square/includes/Gateway/Digital_Wallet.php:462  
Additional context
{
    "error": {
        "type": 1,
        "file": "/public_html/wp-content/plugins/woocommerce-square/includes/Gateway/Digital_Wallet.php",
        "line": 462
    },
    "backtrace": [
        "",
        "#0 /public_html/wp-content/plugins/woocommerce-square/includes/Gateway/Digital_Wallet.php(383): WooCommerce\Square\Gateway\Digital_Wallet->get_product_payment_request(11846)",
        "#1 /public_html/wp-content/plugins/woocommerce-square/includes/Gateway/Digital_Wallet.php(132): WooCommerce\Square\Gateway\Digital_Wallet->get_payment_request_for_context('product')",
        "#2 /public_html/wp-includes/class-wp-hook.php(324): WooCommerce\Square\Gateway\Digital_Wallet->init(Object(WP))",
        "#3 /public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)",
        "#4 /public_html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)",
        "#5 /public_html/wp-includes/class-wp.php(830): do_action_ref_array('wp', Array)",
        "#6 /public_html/wp-includes/functions.php(1336): WP->main('')",
        "#7 /public_html/wp-blog-header.php(16): wp()",
        "#8 /public_html/index.php(17): require('/home/dynamicwe...')",
        "#9 {main}",
        "thrown"
    ]
}
```

### To reproduce

1. Create a simple product
1. enable NYP for that product
1. do not add any prices or minimum prices
2. save product and visit on front end

I'm not seeing this fatal error any longer (or am not sure how to reproduce, just relaying it from the customer's log). I do however, still see a warning pointing to the same line

>Warning: A non-numeric value encountered in /public_html/wp-content/plugins/woocommerce-square/includes/Gateway/Digital_Wallet.php on line 462

The [line in question](https://github.com/woocommerce/woocommerce-square/blob/ef3f98470896b6e40e5100d0ffcbd21162120800/includes/Gateway/Digital_Wallet.php#L462)

```
$amount         = number_format( $quantity * $product->get_price(), 2, '.', '' );
```

If I had to guess, `$product->get_price()` can be a null string if there's no minimum price set. (I'll have to go double check as I _thought_ that I was setting the price to 0, both for sorting AND for math purposes like this). I don't really know what this code is responsible for, but as a name your price product, it technically doesn't have a price until the customer enters one.

**Screenshots**
![image](https://github.com/user-attachments/assets/e4f0e592-6e8b-4504-9a83-62f7d3366505)

**Environment (please complete the following information):**
```
### WordPress Environment ###

WC Version: 9.1.2
Legacy REST API Package Version: ✔ 1.0.4
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1k
```

Square 4.7.1

**Comment by helgatheviking** [comment]
Following up to add that I _do_ set a product's price to be 0 when the minimum is a null string. So if I toggle NYP off and then back on again at their site, my save routine kicks in and 0 is saved as the regular price as intended. This resolves the warning (and I presume the fatal error as well).

**Comment by ChrissiePollock** [comment]
A developer came into support with a similar issue. They share that they use woocommerce-square plugin and have a product that is £0.00. 

The issue is at woocommerce-square/includes/Gateway/Digital_Wallet.php line 462. 

As the number when the price is at 0.00 shows as '0' ( a string ) causing and type error. 

To fix this they adjusted the line to be number_format( $quantity * (float) $product->get_price(), 2, '.', '' ); . adding in the float to fix the type error.

Is this something that could be permanent?

**Comment by jeffpaul** [comment]
@chrissiepollock if you could share a bit more details (e.g. site health info export) and reproduction steps, then we can further triage.  Though perhaps a quick check of that specific line in the codebase and potential handling for 0 pricing can be something we do a quick check on (cc: @vikram.moparthy if you could have someone check that quickly to see if there's some defensive handling we can put in place?)

**Comment by kaushikasomaiya** [comment]
Another report here 10070203-zen
I'll ask for more details.

**Comment by nicdwilson** [comment]
@jeffpaul In the case of 10070203-zd-a8c, the error is occurring when a gift card is in the mix: `YITH WooCommerce Gift Cards Premium: by YITH – 4.26.0`.

```
Fatal error: Uncaught TypeError: Unsupported operand types: int * string in /var/web/site/public_html/wp-content/plugins/woocommerce-square/includes/Gateway/Digital_Wallet.php:462
Stack trace:
#0 /var/web/site/public_html/wp-content/plugins/woocommerce-square/includes/Gateway/Digital_Wallet.php(383): WooCommerce\Square\Gateway\Digital_Wallet->get_product_payment_request(8647) #1 /var/web/site/public_html/wp-content/plugins/woocommerce-square/includes/Gateway/Digital_Wallet.php(132): WooCommerce\Square\Gateway\Digital_Wallet->get_payment_request_for_context(‘product’)
#2 /var/web/site/public_html/wp-includes/class-wp-hook.php(324): WooCommerce\Square\Gateway\Digital_Wallet->init(Object(WP))
#3 /var/web/site/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#4 /var/web/site/public_html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#5 /var/web/site/public_html/wp-includes/class-wp.php(835): do_action_ref_array(‘wp’, Array)
#6 /var/web/site/public_html/wp-includes/functions.php(1342): WP->main(”)
#7 /var/web/site/public_html/wp-blog-header.php(16): wp()
#8 /var/web/site/public_html/index.php(17): require(‘/var/web/site/p…’) #9 {main} thrown in /var/web/site/public_html/wp-content/plugins/woocommerce-square/includes/Gateway/Digital_Wallet.php on line 462
```

We're trying to establish the price applied at the point in question, but it seems that some defensive coding when running the math would do the trick.

**Comment by kaushikasomaiya** [comment]
Seems like there is good protection before the faulty value could reach the multiplication - 

Blank and numeric are allowed prices in Woo core - since YITH uses custom field for its Gift price field - the price stays blank. In typical products, the is_purchasable check returns false value for blank prices therefore Square returns early since it has a check

```
		if ( ! $product->is_purchasable() ) {
			/* translators: 1: product name */
			throw new \Exception( sprintf( esc_html__( 'You cannot purchase "%1$s" because it is currently not available.', 'woocommerce-square' ), esc_html( $product->get_name() ) ) );
		}
```

However, the YITH plugin might have a filter applied on that to make it purchasable which causes blank price to reach the multiplication point.

**Comment by kaushikasomaiya** [comment]
PS Can be replicated with the free version of YITH Gift Cards available on WP.org

**Comment by jeffpaul** [comment]
Thanks for the updated triage info, if y'all narrow down further on the YITH incompatibility and determine there's a fix needed in Square please share so we can work to get this issue prioritized accordingly. (cc: @eclarke1)

**Comment by kaushikasomaiya** [comment]
I do think Square needs to ensure the value is valid before multiplication because blank price is allowed in WooCommerce and even though we have ! $product->is_purchasable() check - the value could reach there like in case of YITH plugin.
